# Generated by Django 5.0.3 on 2024-03-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=10)),
            ],
        ),
    ]
